name: Upload to S3 Bucket

on:
  workflow_dispatch: # Allows for manual trigger from the GitHub UI

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Torque environment
        id: start-environment
        uses: QualiTorque/torque-start-environment@v1
        with:
          space: YourSpaceName
          blueprint_name: YourBlueprintName
          torque_token: ${{ secrets.TORQUE_TOKEN }}
          duration: 120
          timeout: 30

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your AWS region

      - name: Create a test file
        run: echo "Hello from GitHub Actions!" > test-file.txt

      - name: Upload test file to S3
        run: aws s3 cp test-file.txt s3://${{ secrets.S3_BUCKET_NAME }}/

      - name: Verify file upload
        run: aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}/

      - name: End Torque environment
        if: always()
        uses: QualiTorque/torque-end-environment@v1
        with:
          space: YourSpaceName
          environment_id: ${{ steps.start-environment.outputs.environment_id }}
          torque_token: ${{ secrets.TORQUE_TOKEN }}